USE DATN
GO

SELECT * FROM USERS

SELECT * FROM ADDRESSES

INSERT INTO ADMIN (ADMIN_ID, ADMIN_NAME, ADMIN_EMAIL, ADMIN_PHONE, ADMIN_PASSWORD, [ROLE], CREATED_AT, UPDATED_AT) VALUES
('AD_001', N'Admin_CEO', 'tranxuanhoang@gmail.com', '0335404974', 'ePLVdTviufhixXWxdgsf6zzfGag358dk35fbl6qj2s4=', 'CEO', GETDATE(), GETDATE())

SELECT * FROM ADMIN

SELECT * FROM BRANDS

SELECT * FROM CATEGORIES
	insert into CATEGORIES(CATEGORY_NAME, CATEGORY_IMAGE, CATEGORY_STATUS)
	values(N'Vòng tay', '4LNEJ1Z', 'ACTIVE')

SELECT * FROM PRODUCTS

SELECT * FROM PRODUCT_IMAGE

SELECT * FROM DISCOUNT

SELECT * FROM RATE_COMMENT

SELECT * FROM WISHLIST

select * from ORDERS

SELECT * FROM ORDER_DETAILS

SELECT * FROM MENU
 
SELECT * FROM CONTACT

SELECT * FROM TASK

select * from BANNERS

select * from REFRESH_TOKENS

select * from CART

select * from DEVICES

select * from OTP_STORE

SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ORDERS';

select * from PRODUCT_COLOR

select * from PRODUCT_SIZE

select * from ORDER_STATUS

create table SERACH_HISTORY(
	ID int identity(1, 1) primary key,
	[USER_ID] nvarchar(50) not null,
	SEARCH nvarchar(255)
)

select * from GUEST

select * from ROLES

ALTER TABLE PRODUCT_IMAGE
ADD CONSTRAINT fk_image_product
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


DELETE FROM PRODUCT_IMAGE
WHERE PRODUCT_ID NOT IN (SELECT PRODUCT_ID FROM PRODUCTS);

SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('USERS') AND COLUMN_NAME = 'USER_ID';

alter table DEVICES
alter column USER_ID nvarchar(255)

select * from DEVICES
select * from USERS where USER_LAST_NAME = 'Tran'
select * from PRODUCTS where BRAND_ID = 1
