USE DATN
GO

CREATE TABLE USERS (
    [USER_ID] NVARCHAR(255) PRIMARY KEY,
    [USER_FIRST_NAME] NVARCHAR(100) NOT NULL,
	USER_LAST_NAME NVARCHAR(100) NOT NULL,
	USER_GENDER NVARCHAR (255),
    USER_EMAIL NVARCHAR(150) UNIQUE NOT NULL,
	USER_PHONE NVARCHAR(20) UNIQUE NOT NULL,
    USER_PASSWORD NVARCHAR(255) NOT NULL,
    CREATE_DT DATETIME DEFAULT GETDATE()
);
SELECT * FROM USERS

CREATE TABLE ADDRESSES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID NVARCHAR(255) NOT NULL,
    HOUSE_NUMBER NVARCHAR(255) NOT NULL,
    STREET NVARCHAR(255) NOT NULL,
    CITY NVARCHAR(255) NOT NULL,
    POSTAL_CODE VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,
    TYPE_ADDRESS NVARCHAR(255) NOT NULL,
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME DEFAULT GETDATE()
);

SELECT * FROM ADDRESSES

CREATE TABLE ADMIN (
    ADMIN_ID NVARCHAR(50) PRIMARY KEY,
    ADMIN_NAME NVARCHAR(255) NOT NULL,
    ADMIN_EMAIL NVARCHAR(255) UNIQUE NOT NULL,
    ADMIN_PHONE NVARCHAR(20) UNIQUE NOT NULL,
    ADMIN_PASSWORD NVARCHAR(255) NOT NULL,
    [ROLE] NVARCHAR(50) NOT NULL,
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME DEFAULT GETDATE()
);

INSERT INTO ADMIN (ADMIN_ID, ADMIN_NAME, ADMIN_EMAIL, ADMIN_PHONE, ADMIN_PASSWORD, [ROLE], CREATED_AT, UPDATED_AT) VALUES
('AD_001', N'Admin_CEO', 'tranxuanhoang@gmail.com', '0335404974', 'ePLVdTviufhixXWxdgsf6zzfGag358dk35fbl6qj2s4=', 'CEO', GETDATE(), GETDATE())

SELECT * FROM ADMIN


SELECT * FROM BRANDS


SELECT * FROM CATEGORIES


SELECT * FROM PRODUCTS


SELECT * FROM PRODUCT_IMAGE


SELECT * FROM DISCOUNT


SELECT * FROM RATE_COMMENT



SELECT * FROM STOCK

CREATE TABLE WISHLIST (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	[USER_ID] NVARCHAR(50) NOT NULL,
	PRODUCT_ID INT UNIQUE NOT NULL,
	CREATED_AT DATETIME DEFAULT GETDATE()
)

SELECT * FROM WISHLIST


select * from orders


SELECT * FROM ORDER_DETAILS




SELECT * FROM MENU
 
CREATE TABLE CONTACT (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	USER_EMAIL NVARCHAR(255),
	[USER_NAME] NVARCHAR(255),
	TITLE NVARCHAR(255),
	CONTENT NVARCHAR(MAX),
	CONTACT_STATUS NVARCHAR(20),
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME DEFAULT GETDATE()
)

SELECT * FROM CONTACT



SELECT * FROM TASK



select * from BANNER