SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[USER_Register] 
	@p_USER_DATA_JSON NVARCHAR(MAX)
AS
BEGIN
SET NOCOUNT ON;
BEGIN TRANSACTION;
BEGIN TRY
	-- Get data JSON
	DECLARE  @p_USER_ID NVARCHAR (255),
			 @p_USER_FIRST_NAME NVARCHAR(255),
			 @p_USER_LAST_NAME NVARCHAR(255),
			 @p_USER_GENDER NVARCHAR(255),
			 @p_USER_EMAIL NVARCHAR(255),
			 @p_USER_PHONE NVARCHAR(255),
			 @p_USER_PASSWORD NVARCHAR(255)

	SELECT	 @p_USER_ID = UserId, 
			 @p_USER_FIRST_NAME = UserFirstName,
			 @p_USER_LAST_NAME = UserLastName,
			 @p_USER_GENDER = UserGender,
			 @p_USER_EMAIL = UserEmail,
			 @p_USER_PHONE = UserPhone,
			 @p_USER_PASSWORD = UserPassword
	FROM OPENJSON(@p_USER_DATA_JSON)
	WITH(
		UserId NVARCHAR(255) '$.USER_ID',
		UserFirstName NVARCHAR(255) '$.USER_FIRST_NAME',
		UserLastName NVARCHAR(255) '$.USER_LAST_NAME',
		UserGender NVARCHAR(255) '$.USER_GENDER',
		UserEmail NVARCHAR(255) '$.USER_EMAIL',
		UserPhone NVARCHAR(18) '$.USER_PHONE',
		UserPassword NVARCHAR(255) '$.USER_PASSWORD'
	);

	-- CHECK VALUE INPUT
	IF EXISTS (SELECT 1 FROM [dbo].[USERS] WHERE [USER_EMAIL] = @p_USER_EMAIL)
	BEGIN
		RAISERROR('Email đã tồn tại', 16, 1)
		ROLLBACK TRANSACTION;
		RETURN;
	END
	IF EXISTS (SELECT 1 FROM [dbo].[USERS] WHERE [USER_PHONE] = @p_USER_PHONE)
	BEGIN
		RAISERROR('Email đã tồn tại', 16, 1)
		ROLLBACK TRANSACTION;
		RETURN;
	END

	-- CREATE USER
	INSERT INTO [dbo].[USERS] ([USER_ID], [USER_FIRST_NAME], USER_LAST_NAME, [USER_GENDER], [USER_EMAIL], [USER_PHONE], [USER_PASSWORD])
	VALUES (@p_USER_ID, @p_USER_FIRST_NAME, @p_USER_LAST_NAME, @p_USER_GENDER, @p_USER_EMAIL, @p_USER_PHONE, @p_USER_PASSWORD)

	--
	SELECT USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_PHONE 
        FROM [dbo].[USERS]
        WHERE USER_ID = @p_USER_ID;
	COMMIT TRANSACTION;
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION;
	PRINT ERROR_MESSAGE();
END CATCH
END
GO