SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ADDRESS_Get] 
	@p_USER_ID NVARCHAR(255)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT [HOUSE_NUMBER], [STREET], CITY, POSTAL_CODE, COUNTRY, TYPE_ADDRESS
	FROM [dbo].[ADDRESSES]
	WHERE [USER_ID] = @p_USER_ID
END
GO