SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRODUCT_List]
	@p_PRODUCT_DATA_JSON NVARCHAR(MAX),
	@p_TOTAL_RECORD INT OUTPUT

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE	 @p_PAGE_NUMBER INT,
			 @p_PAGE_SIZE INT

	SELECT	 @p_PAGE_NUMBER = PageNumber,
			 @p_PAGE_SIZE = PageSize
	FROM OPENJSON(@p_PRODUCT_DATA_JSON)
	WITH(
		PageNumber INT '$.PAGE_NUMBER',
		PageSize INT '$.PAGE_SIZE'
	)

	SELECT @p_TOTAL_RECORD = COUNT(*) FROM PRODUCTS

	SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P_I.IMAGE_NAME, P.PRODUCT_PRICE, P.PRODUCT_STATUS
	FROM PRODUCTS P, PRODUCT_IMAGE P_I
	WHERE P_I.PRODUCT_ID = P.PRODUCT_ID
	ORDER BY P.PRODUCT_ID
	OFFSET (@p_PAGE_NUMBER - 1) * @p_PAGE_SIZE ROWS
	FETCH NEXT @p_PAGE_SIZE ROWS ONLY
END
GO