SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ORDER_Update]
	@p_ORDER_ID nvarchar(20),
	@p_ORDER_STATUS nvarchar(20)
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRANSACTION
	BEGIN TRY
		IF NOT EXISTS (SELECT 1 FROM ORDERS WHERE ID = @p_ORDER_ID)
		BEGIN
			ROLLBACK TRANSACTION
			SELECT N'Mã đơn hàng không tồn tại' AS RESULT,
				   404 AS CODE
			RETURN
		END

		IF EXISTS (SELECT 1 FROM ORDERS WHERE ID = @p_ORDER_ID AND ORDER_STATUS = 'Completed')
		BEGIN
			ROLLBACK TRANSACTION
			SELECT N'Đơn hàng đã được hoàn thành' AS RESULT,
				   409 AS CODE
			RETURN
		END

		UPDATE ORDERS
		SET ORDER_STATUS = @p_ORDER_STATUS,
			UPDATED_AT = GETDATE()
		WHERE ID = @p_ORDER_ID

		IF @@ROWCOUNT = 0
		BEGIN
			ROLLBACK TRANSACTION
			SELECT N'Cập nhật thất bại' AS RESULT,
				   500 AS CODE
			RETURN
		END

		COMMIT TRANSACTION
		SELECT N'Cập nhật thành công' AS RESULT,
			   200 AS CODE
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		SELECT ERROR_MESSAGE() AS RESULT,
			   ERROR_NUMBER() AS CODE
	END CATCH
END
GO