SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[WISHLIST_List] 
	@p_USER_ID NVARCHAR(20)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT P.PRODUCT_NAME, P.PRODUCT_PRICE, P_I.IMAGE_NAME
	FROM WISHLIST W
	LEFT JOIN PRODUCTS P ON W.PRODUCT_ID = P.PRODUCT_ID
	LEFT JOIN PRODUCT_IMAGE P_I ON W.PRODUCT_ID = P_I.PRODUCT_ID
	WHERE W.[USER_ID] = @p_USER_ID
END
GO