SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RATE_COMMENT_List] 
	@p_PRODUCT_ID INT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	SET NOCOUNT ON;
	IF @p_PRODUCT_ID IS NULL
    BEGIN
        RAISERROR('Product ID cannot be NULL', 16, 1);
        RETURN;
    END

    IF NOT EXISTS (SELECT 1 FROM PRODUCTS WHERE PRODUCT_ID = @p_PRODUCT_ID)
    BEGIN
        RAISERROR('No product found for Product ID: %d', 16, 1, @p_PRODUCT_ID);
        RETURN;
    END

	SELECT U.USER_LAST_NAME, R_C.RATE, R_C.COMMENT
	FROM RATE_COMMENT R_C
	INNER JOIN PRODUCTS P ON R_C.PRODUCT_ID = P.PRODUCT_ID
	INNER JOIN USERS U ON R_C.[USER_ID] = U.[USER_ID]
	WHERE R_C.PRODUCT_ID = @p_PRODUCT_ID
END
GO