SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[WISHLIST_Delete] 
	@p_USER_ID NVARCHAR(20),
	@p_PRODUCT_ID INT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    BEGIN TRANSACTION
	BEGIN TRY
		IF @p_USER_ID IS NULL OR LTRIM(RTRIM(@p_USER_ID)) = ''
		BEGIN
			RAISERROR(N'USER_ID không được để trống.', 16, 1)
			RETURN
		END

		IF @p_PRODUCT_ID IS NULL
		BEGIN
			RAISERROR(N'PRODUCT_ID không được để trống.', 16, 1)
			RETURN
		END

		IF NOT EXISTS (SELECT 1 FROM WISHLIST WHERE [USER_ID] = @p_USER_ID AND PRODUCT_ID = @p_PRODUCT_ID)
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR(N'Sản phẩm không tồn tại trong mục yêu thích.', 16, 1)
			RETURN
		END

		DELETE FROM WISHLIST
		WHERE [USER_ID] = @p_USER_ID 
		AND PRODUCT_ID = @p_PRODUCT_ID

		SELECT @@ROWCOUNT AS RowsAffected

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		PRINT ERROR_MESSAGE()
		RETURN
	END CATCH
	
END
GO