SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[PRODUCT_Detail]
	@p_PRODUCT_ID INT 
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		-- Kiểm tra sản phẩm có tồn tại không
		IF NOT EXISTS (SELECT 1 FROM PRODUCTS WHERE PRODUCT_ID = @p_PRODUCT_ID)
		BEGIN
			RETURN;
		END
		
		-- Lấy thông tin chi tiết sản phẩm và ảnh (dùng INNER JOIN, giới hạn 1 ảnh)
		SELECT TOP 1 
			P.PRODUCT_NAME, 
			P_I.IMAGE_NAME, 
			P.PRODUCT_PRICE, 
			P.PRODUCT_DETAIL, 
			P.PRODUCT_DESCRIPTION
		FROM PRODUCTS P
		INNER JOIN PRODUCT_IMAGE P_I ON P.PRODUCT_ID = P_I.PRODUCT_ID
		WHERE P.PRODUCT_ID = @p_PRODUCT_ID;

	END TRY
	BEGIN CATCH
		PRINT ERROR_MESSAGE();
		RETURN;
	END CATCH
END
GO