SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ORDER_DETAIL_ById]
	@p_ORDER_ID nvarchar(20)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SELECT 
    P.PRODUCT_NAME, 
    P_I.IMAGE_NAME, 
    O_D.QUANTITY, 
    O_D.SUBTOTAL, 
    O_D.ORDER_ID
	FROM ORDER_DETAILS O_D
	LEFT JOIN PRODUCTS P ON O_D.PRODUCT_ID = P.PRODUCT_ID
	LEFT JOIN PRODUCT_IMAGE P_I ON O_D.PRODUCT_ID = P_I.PRODUCT_ID

	where ORDER_ID = @p_ORDER_ID
    

END
GO