SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[BRAND_Create]
	@p_BRAND_DATA_JSON NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRANSACTION

	BEGIN TRY
		DECLARE  @p_ADMIN_ID NVARCHAR(20),
				 @p_BRAND_NAME NVARCHAR(255),
				 @p_BRAND_IMAGE NVARCHAR(MAX),
				 @p_BRAND_STATUS NVARCHAR(10)

		SELECT   @p_ADMIN_ID = ADMIN_ID,
				 @p_BRAND_NAME = BrandName,
				 @p_BRAND_IMAGE = BrandImage,
				 @p_BRAND_STATUS = BrandStatus
		FROM OPENJSON(@p_BRAND_DATA_JSON)
		WITH(
			ADMIN_ID nvarchar(20) '$.ADMIN_ID',
			BrandName NVARCHAR(255) '$.BRAND_NAME',
			BrandImage NVARCHAR(MAX) '$.BRAND_IMAGE',
			BrandStatus NVARCHAR(10) '$.BRAND_STATUS'
		)

		IF @p_BRAND_DATA_JSON IS NULL OR @p_BRAND_DATA_JSON = ''
        BEGIN
			ROLLBACK TRANSACTION
			select N'Dữ liệu trống' as RESULT,
					422 as CODE
			RETURN
        END

		IF EXISTS (SELECT 1 FROM BRANDS WHERE BRAND_NAME = @p_BRAND_NAME)
		BEGIN
			ROLLBACK TRANSACTION
			select N'Tên thương hiệu đã tồn tại' as RESULT,
					409 as CODE
			RETURN;
		END

		declare @p_ROLE_RESULT nvarchar(10)
		exec [dbo].[CHECK_ROLE] @p_ADMIN_ID = @p_ADMIN_ID, @p_RESULT = @p_ROLE_RESULT output

		IF @p_ROLE_RESULT <> 1
		begin
			rollback transaction
			select N'Không đủ quyền' as RESULT,
					403 as CODE
			return
		end

		INSERT INTO BRANDS (BRAND_NAME, BRAND_IMAGE, BRAND_STATUS)
            VALUES (@p_BRAND_NAME, @p_BRAND_IMAGE, ISNULL(@p_BRAND_STATUS, 'INACTIVE'));

		IF @@ROWCOUNT <> 0
		BEGIN
			COMMIT TRANSACTION
			SELECT BRAND_ID, BRAND_NAME, BRAND_IMAGE, BRAND_STATUS, N'Tạo thương hiệu thành công' as RESULT, 201 as CODE
			FROM BRANDS
			WHERE BRAND_NAME = @p_BRAND_NAME
			
		END

	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		select  ERROR_MESSAGE() as RESULT,
				ERROR_NUMBER() as CODE
	END CATCH
END
GO