SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[USER_Inf]
	@p_USER_ID NVARCHAR(255)
AS
BEGIN
	SET NOCOUNT ON;
    -- Insert statements for procedure here
	SELECT [USER_FIRST_NAME], USER_LAST_NAME, USER_GENDER, [USER_EMAIL], [USER_PHONE]
	FROM [dbo].[USERS]
	WHERE [USER_ID] = @p_USER_ID
END
GO