SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[WISHLIST_Create]
	@p_PRODUCT_ID INT,
	@p_USER_ID NVARCHAR(20)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	BEGIN TRANSACTION
	BEGIN TRY
		IF NOT EXISTS (SELECT 1 FROM USERS WHERE [USER_ID] = @p_USER_ID)
		BEGIN 
			ROLLBACK TRANSACTION
			RAISERROR(N'Không thể thêm sản phẩm vào mục yêu thích', 16, 1)
			RETURN
		END

		IF EXISTS (SELECT 1 FROM WISHLIST WHERE [USER_ID] = @p_USER_ID AND PRODUCT_ID = @p_PRODUCT_ID)
		BEGIN
			ROLLBACK TRANSACTION
			RAISERROR('Sản phẩm đã được thêm vào mục yêu thích', 16, 1)
			RETURN
		END

		INSERT INTO WISHLIST ([USER_ID], PRODUCT_ID, CREATED_AT)
		VALUES (@p_USER_ID, @p_PRODUCT_ID, GETDATE())

			SELECT [USER_ID], PRODUCT_ID, CREATED_AT
			FROM WISHLIST
			WHERE [USER_ID] = @p_USER_ID 
			AND PRODUCT_ID = @p_PRODUCT_ID
			
			COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		PRINT ERROR_MESSAGE()
		RETURN
	END CATCH
END
GO