SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[RATE_COMMENT_List] 
	@p_PRODUCT_ID INT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	SET NOCOUNT ON;
	IF @p_PRODUCT_ID IS NULL
    BEGIN
        select N'Mã sản phẩm không được để trống' as RESULT,
				422 as CODE
        RETURN;
    END

    IF NOT EXISTS (SELECT 1 FROM PRODUCTS WHERE PRODUCT_ID = @p_PRODUCT_ID)
    BEGIN
        select N'Không tồn tại sản phẩm cần đánh giá ' as RESULT,
				404 as CODE
        RETURN;
    END

	SELECT U.USER_LAST_NAME, R_C.RATE, R_C.COMMENT
	FROM RATE_COMMENT R_C
	INNER JOIN PRODUCTS P ON R_C.PRODUCT_ID = P.PRODUCT_ID
	INNER JOIN USERS U ON R_C.[USER_ID] = U.[USER_ID]
	WHERE R_C.PRODUCT_ID = @p_PRODUCT_ID
END
GO