SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[USER_Up]
	@p_USER_DATA_JSON NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRANSACTION
	BEGIN TRY
		DECLARE  @p_USER_ID NVARCHAR(255),
				 @p_USER_NAME NVARCHAR(255),
				 @p_USER_EMAIL NVARCHAR(255),
				 @p_USER_PHONE NVARCHAR(255)

		SELECT  @p_USER_ID = UserId,
				@p_USER_NAME = UserName,
				@p_USER_EMAIL = UserEmail,
				@p_USER_PHONE = UserPhone
		FROM OPENJSON(@p_USER_DATA_JSON)
		WITH (  UserId NVARCHAR(255) '$.USER_ID',
				UserName NVARCHAR(255) '$.USER_NAME',
				UserEmail NVARCHAR(255) '$.USER_EMAIL',
				UserPhone NVARCHAR(255) '$.USER_PHONE'
			);	

		IF EXISTS(SELECT 1 FROM USERS WHERE [USER_ID] = @p_USER_ID)
		BEGIN
			UPDATE USERS
			SET  [USER_NAME] = @p_USER_NAME,
				 [USER_EMAIL] = @p_USER_EMAIL,
				 [USER_PHONE] = @p_USER_PHONE
			WHERE [USER_ID] = @p_USER_ID
		END

		---
		SELECT [USER_NAME], [USER_EMAIL], [USER_PHONE]
		FROM USERS
		WHERE [USER_ID] = @p_USER_ID
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		PRINT ERROR_MESSAGE()
	END CATCH
END
GO