CREATE TABLE [dbo].[BRANDS] (
  [BRAND_ID] [int] IDENTITY,
  [BRAND_NAME] [nvarchar](50) NOT NULL,
  [BRAND_IMAGE] [nvarchar](max) NOT NULL,
  [BRAND_STATUS] [nvarchar](10) NULL DEFAULT ('INACTIVE'),
  [CREATED_AT] [datetime] NULL DEFAULT (getdate()),
  [UPDATE_AT] [datetime] NULL DEFAULT (getdate()),
  PRIMARY KEY CLUSTERED ([BRAND_ID]),
  UNIQUE ([BRAND_NAME]),
  CHECK ([BRAND_STATUS]='INACTIVE' OR [BRAND_STATUS]='ACTIVE')
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO