CREATE TABLE [dbo].[PRODUCTS] (
  [PRODUCT_ID] [int] IDENTITY,
  [PRODUCT_NAME] [nvarchar](50) NOT NULL,
  [PRODUCT_PRICE] [decimal](10, 2) NOT NULL,
  [PRODUCT_DETAIL] [nvarchar](max) NOT NULL,
  [PRODUCT_DESCRIPTION] [nvarchar](max) NOT NULL,
  [BRAND_ID] [int] NOT NULL,
  [CATEGORY_ID] [int] NOT NULL,
  [PRODUCT_STATUS] [nvarchar](10) NULL DEFAULT ('INACTIVE'),
  [CREATED_AT] [datetime] NULL DEFAULT (getdate()),
  [UPDATED_AT] [datetime] NULL DEFAULT (getdate()),
  PRIMARY KEY CLUSTERED ([PRODUCT_ID]),
  CHECK ([PRODUCT_STATUS]='INACTIVE' OR [PRODUCT_STATUS]='ACTIVE')
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO