CREATE TABLE [dbo].[CATEGORIES] (
  [CATEGORY_ID] [int] IDENTITY,
  [CATEGORY_NAME] [nvarchar](50) NOT NULL,
  [CATEGORY_IMAGE] [nvarchar](max) NOT NULL,
  [CATEGORY_STATUS] [nvarchar](10) NULL DEFAULT ('INACTIVE'),
  [CREATED_AT] [datetime] NULL DEFAULT (getdate()),
  [UPDATE_AT] [datetime] NULL DEFAULT (getdate()),
  PRIMARY KEY CLUSTERED ([CATEGORY_ID]),
  UNIQUE ([CATEGORY_NAME]),
  CHECK ([CATEGORY_STATUS]='INACTIVE' OR [CATEGORY_STATUS]='ACTIVE')
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO