CREATE TABLE [dbo].[PRODUCT_IMAGE] (
  [IMAGE_ID] [int] IDENTITY,
  [IMAGE_NAME] [nvarchar](255) NOT NULL,
  [PRODUCT_ID] [int] NOT NULL,
  [IMAGE_STATUS] [nvarchar](10) NULL DEFAULT ('INACTIVE'),
  [CREATE_AT] [datetime] NULL DEFAULT (getdate()),
  [UPDATED_AT] [datetime] NULL DEFAULT (getdate()),
  PRIMARY KEY CLUSTERED ([IMAGE_ID]),
  CHECK ([IMAGE_STATUS]='INACTIVE' OR [IMAGE_STATUS]='ACTIVE')
)
ON [PRIMARY]
GO