CREATE TABLE [dbo].[DISCOUNT] (
  [DISCOUNT_ID] [int] IDENTITY,
  [PRODUCT_ID] [int] NOT NULL,
  [DISCOUNT_PERCENT] [decimal](10, 2) NOT NULL,
  [START_DT] [date] NULL,
  [END_DT] [date] NULL,
  [DISCOUNT_STATUS] [nvarchar](10) NULL DEFAULT ('INACTIVE'),
  [CREATED_AT] [datetime] NULL DEFAULT (getdate()),
  [UPDATED_AT] [datetime] NULL DEFAULT (getdate()),
  PRIMARY KEY CLUSTERED ([DISCOUNT_ID]),
  CHECK ([DISCOUNT_PERCENT]<(100)),
  CHECK ([DISCOUNT_STATUS]='INACTIVE' OR [DISCOUNT_STATUS]='ACTIVE')
)
ON [PRIMARY]
GO